version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: xstore-g4f_server_1
      APP_PORT: 8080

  server:
    image: hlohaus789/g4f:latest
    shm_size: 2gb
    ports:
      - "8080:8080"
      - "1337:1337"
      - "7900:7900"
