version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: xstore-homepage-server
      APP_PORT: 3000

  server:
    image: ghcr.io/gethomepage/homepage:v0.9.3
    volumes:
      - ${APP_DATA_DIR}/data/homepage:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # (optional) For docker integrations